name: Build package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate version.json
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(git log -1 --format=%cI)

          echo "{ \"commit\": \"$COMMIT\", \"date\": \"$DATE\" }" > version.json

      - name: Create zip
        run: |
          zip -r project.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-build
          path: project.zip
